### ISSUE TITLE
Render Straight Molecular Graph

### ISSUE THREAD

**Issue by qbKhanh** [epam/Indigo#1374]
**Background**
I want to generate straight molecular graph from SMILES string like that `CCCCC` or `CC=CCCC`, etc. In your result, The symbol of Carbon atoms are up and down respectively, but I want to all in a row

**Solution**
I want all symbols are generated in a row, more than that I can custom the position of symbol

**Alternatives**
N/A

**Additional context**
The image from your repo
![image](https://github.com/epam/Indigo/assets/90884691/c556a04e-051c-42ac-aed6-be51f5e7ff8f)
The image that I want
![image](https://github.com/epam/Indigo/assets/90884691/702f709e-5f57-4a69-82c1-be0c6c37d2db)

Thank for your great hard-working!
Hope for your reply soon!
Best regards,
Khanh

**Comment by AlexanderSavelyev** [comment]
could you please inform why do you need this representation? Indigo uses IUPAC style where straight line for single bonds is an incorrect view (since it can affect linear bond issue for stereo) so it should be 120 degrees between bonds
Indigo also supports exceptions for linear double bonds e.g C=C=C
![image](https://github.com/epam/Indigo/assets/7427808/029915ea-8cf1-46e8-b5b8-a2c5485ca95a)
and liner triple bonds e.g. C#C-C#C
![image](https://github.com/epam/Indigo/assets/7427808/1fe0d3c7-1261-4c91-8250-91b5f34d8382)
Unfortunately we can't create such a layout without clear requirement description

**Comment by qbKhanh** [comment]
Hi @AlexanderSavelyev ,
I am doing a project that can recognize chemical structure with Chemistry at the Vietnamese high school level. And the data is mainly like I proposed first. I want to use your tool to augment my data.

Following are more examples:
![Screenshot from 2023-09-18 12-20-25](https://github.com/epam/Indigo/assets/90884691/d2854731-2bc2-4295-9869-7c9df4a13baf)
![Screenshot from 2023-09-18 12-27-24](https://github.com/epam/Indigo/assets/90884691/013bdece-7273-4975-8336-01d92452b48f)
![Screenshot from 2023-09-18 15-53-02](https://github.com/epam/Indigo/assets/90884691/95c94074-d757-4981-9cd4-4cd5a707cc90)

I really need your help!
Best regards,
Khanh

**Comment by AlexanderSavelyev** [comment]
Unfortunately, it is very specific requirement to be implemented

The only thing I can suggest is to create a python script and use the Indigo API to change the coordinates manually
https://lifescience.opensource.epam.com/indigo/api/index.html#modifying-atoms-and-bonds
atom.setXYZ()
e.g.
call layout()
change setXYZ() for atoms
call render()

Calculation the coordinates can be a simple geometrical task after calling a layout first
e.g. if angle is 120 and two neighbor atoms then make angle 180 
if angle is 120 and three neighbors then make 90
etc,

**Comment by qbKhanh** [comment]
Dear @AlexanderSavelyev @tbwxmu, 

Thanks for spending time on my problem! 
I solved my problem by converting SMILES string into chemfig in LaTex then using some rule-based algorithms to modify the position of each bond. 

Best regards,
Khanh
