### ISSUE TITLE
api: ECFP6 fingerprints on macOS differ from the same on Windows and Linux

### ISSUE THREAD

**Issue by mkviatkovskii** [epam/Indigo#207]
Python Tests:
* todo/fingerprints_morgan-fingerprints.py
* todo/similarity_morgan_ecfp.py

See https://github.com/epam/Indigo/runs/1332678403?check_suite_focus=true

**Comment by yuriiq** [comment]
This difference occurs because atom.bond_descriptors sorts by MoleculeMorganFingerprintBuilder::bondDescriptorCmp where the order is given as int(dword-dword).
If a < 2^30 and c > 2^31+2^30 then c - a > 2^31 and int(c-a) < 0

If the input array has the following elements:
a ∈ (0; 2^30)
b ∈ (2^30; 2^31)
c ∈ (2^31+2^30; 2^32)

MoleculeMorganFingerprintBuilder::bondDescriptorCmp will return the following results: 
f(a, b) < 0
f(b, c) < 0
f(c, a) < 0

The order of the elements in this case depends on std::sort implementation and the input array's elements order.

In addition, hash values are stored in dword, which define as unsigned int. This can create additional problems because sizeof(unsigned int) can be different on different systems.
In such cases it is strong recommended to use uint32_t from stdint.h  or std::uint32_t form cstdint.

**Comment by even1024** [comment]
Fixed in Release 1.5
