### ISSUE TITLE
System replace arrows of diffrent types with Open Arrow type while loading from PPTX(CDX)

### ISSUE THREAD

**Issue by AlexeyGirin** [epam/Indigo#2232]
**Steps to Reproduce**
1. Click Open... button (Ctrl+O)
2. Select open from file
3. Select file: [ARROWS.pptx](https://github.com/epam/Indigo/files/14449345/ARROWS.pptx) (CDXML extracted: [2232 issue - Arrows.zip](https://github.com/user-attachments/files/16624363/2232.issue.-.Arrows.zip) )

4. Select Structure 1
5. Click Open as New Project

**Actual behavior**
System replace arrows of diffrent types with Open Arrow type
![image](https://github.com/user-attachments/assets/4eaaf4e1-d2c0-408b-809e-5673da05865f)

**Expected behavior**
Something that is looks like source file
![image](https://github.com/user-attachments/assets/82b4ea6c-116c-489c-a678-c354e3ae72a1)

**Environment details:**
- Ketcher Version 2.18.0-rc.9 Build at 2024-02-27; 16:16:47
- Indigo Toolkit Version 1.18.0-rc.9.0-gc7efb4e71-x86_64-linux-gnu-11.2.1
- Chrome Version 122.0.6261.70 (Official Build) (64-bit)
- Win10
- Issue found while testing https://github.com/epam/ketcher/issues/3914

**Comment by split-ends** [comment]
Since the expected behavior was not specified anywhere, I reached out to @AlexeyGirin, who kindly provided me with the following mapping (which works in both directions):
![image](https://github.com/user-attachments/assets/a9cb907c-dec0-4622-a8ea-875e18c23886)

Based on this, I notice that one expected result does not match the actual one when reading from the .pptx document:
![image](https://github.com/user-attachments/assets/d5a2a6a4-e749-4133-a467-ce37e33af88d)

Moreover, it seems that some logic for converting other variants is still missing and needs clarification (analysis):
![image](https://github.com/user-attachments/assets/79986842-52df-45f9-ab5e-cbe53ed6abd9)

Therefore, a bug was created based on this:
