### ISSUE TITLE
Preview: The middle tail of Multi-Tailed Arrow is displayed not in the middle after loading from RDF file

### ISSUE THREAD

**Issue by ivanmaslow** [epam/Indigo#2413]
**Steps to Reproduce**
1. Add to Canvas reaction 3:1 with 3 reactants and 1 product:
[!issue-load-middle-tail.zip](https://github.com/user-attachments/files/17075133/issue-load-middle-tail.zip)

**Actual Result**
- Middle tail isn't in the middle of spine:
![image](https://github.com/user-attachments/assets/32123708-4082-4328-9e21-a8cee6781e70)

**Expected Result**
- Middle tail is in the middle of spine:

**Environment details**
- Tested on CI-CD 2237-detect-pathway SA environment
- Ketcher [Version 2.25.0-rc.2] Build at 2024-09-20; 03:00:51
- Indigo Version 1.25.0-dev.1.57-gdf86cde5-wasm32-wasm-clang-12.0.0
- Windows 11 Enterprise 
- Chrome Version 129.0.6668.59 (Official Build) (64-bit)

**Notes**
- Issue is detected during exploratory testing of Load RDF feature for cascade reactions - https://github.com/epam/Indigo/issues/2102

**Comment by yauhen-karmyzau** [comment]
Expected behaviour, as tails and head arrow are not connected. We are building layout the following way:

1. Positioning reactants with their default horizontal and vertical margin.
2. Positioning tails to be vertically aligned with centres of reactants.
3. Positioning head arrow to be centred vertically re multi-tailed arrow hight.
