### ISSUE TITLE
Preview: Text above reaction arrow ignores margins when atoms are added

### ISSUE THREAD

**Issue by Zhirnoff** [epam/Indigo#2610]
**Steps to Reproduce**
1. Copy and Paste on canvas
```
$RDFILE 1
$DATM    11/05/24 15:07
$RFMT
$RXN

 -INDIGO- 1105241507

  2  1
$MOL

  -INDIGO-11052415072D

  1  0  0  0  0  0  0  0  0  0999 V2000
    7.6474   -4.4514    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
M  END
$MOL

  -INDIGO-11052415072D

  1  0  0  0  0  0  0  0  0  0999 V2000
    7.3724   -6.9764    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
M  END
$MOL

  -INDIGO-11052415072D

  1  0  0  0  0  0  0  0  0  0999 V2000
    9.9974   -5.7764    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0
M  END

$DTYPE Name
$DATUM Agrsthtyjyil9op98p90i6yrtrwwr6u579po9
$DTYPE Reference
$DATUM Not available
$DTYPE Reaction Conditions
$DATUM Agrsthtyjyil9op98p90i6yrtrwwr6u579po9
```

**Actual behavior**
Text above reaction arrow ignores margins when atoms are added

**Expected behavior**
The text should maintain proper margins above the arrow, with sufficient spacing as described in requrements.

**Screenshots**
![2024-11-05_15h14_17](https://github.com/user-attachments/assets/ca2dccdb-c8d0-44dc-8132-8d9ca2d32491)

**Desktop:**
 - OS: Windows 11
 - Browser Chrome
 - Version 128.0.6613.120 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.26.0-rc.7]
**Indigo version** 
[Version 1.27.0-dev.1]

Bug foun while pre-testing: https://github.com/epam/Indigo/issues/2559

**Comment by ivanmaslow** [comment]
The fix is successfully verified on aws_ci SA env with Ketcher-master and Indigo-2404-ket-to-rdf branches:
- Ketcher [Version 2.28.0-dev.1] Build at 2024-11-20; 19:58:39;
- Indigo Version 1.27.0-dev.1.43-gec603913-wasm32-wasm-clang-12.0.0
- Desktop, Windows 11 Enterprise
- Chrome Version 131.0.6778.86 (Official Build) (64-bit)

Reaction's name and conditions are displayed correctly after save/load to/from RDF or layout actions:
![image](https://github.com/user-attachments/assets/831bce9a-e1fd-4c93-9e4f-16e4519cd523)
Also, looks like it could fix  https://github.com/epam/Indigo/issues/2610, but length of spine becomes bigger

**Comment by Zhirnoff** [comment]
Tested. Bug fixed.

![2024-12-05_18h28_27](https://github.com/user-attachments/assets/32058052-08ef-4fbb-8e0f-a9f9434a2352)

**Desktop:**
 - OS: Windows 11
 - Browser Chrome
 - Version 128.0.6613.120 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.28.0-rc.1]
**Indigo version** 
[Version 1.27.0-rc.1]
