### ISSUE TITLE
difference of SMILES between ketcher and Indigo

### ISSUE THREAD

**Issue by biotech7** [epam/Indigo#288]
Hi, team.
   i use webclient(HTML) of ketcher to generate SMILES. but for the same molecule, it is different from the SMILES generated by Indigo Server(JAVA platform). For example:
   for the same molecule: 4-(2-ethylbutanoyl)-1-phenylpiperazin-2-one
  webclient SMILES:  C1=CC=CC(N2C(=O)CN(C(=O)C(CC)CC)CC2)=C1
 Indigo Server(JAVA platform) SMILES:  C(C(CC)C(N1CCN(C2C=CC=CC=2)C(=O)C1)=O)C

  so how can i get the unique/same SMILES from Indigo Server？thanks！

**Comment by AlexanderSavelyev** [comment]
G'day

Following statements are applicable for the SMILES generation
1. SMILES can be different for the same structure even by it's nature
2.  One should use "Canonical" SMILES in order to get uniqueness.
3. Ketcher uses own JS code to generate SMILES string. There is no canonicalization available in Ketcher
4. One should use canonicalSmiles() method from Indigo Java API to receive unique SMILES. There is no way to return same string from Ketcher and Indigo
5. We are in progress of releasing Indigo WASM module which is Indigo JS API (canonicalSmiles will be available as well) so please keep in touch.

Thanks
Alexander

**Comment by biotech7** [comment]
thanks for detailed explanation. long for release Indigo WASM modules.
