### ISSUE TITLE
how to verify  a mixture of structures from a SMILES?

### ISSUE THREAD

**Issue by biotech7** [epam/Indigo#289]
Hi,
    I want to confirm whether it(SMILES) contains a mixture or not. 、
   for example：[Na+].CCCC(CCC)C([O-])=O.CCCC(CCC)C(O)=O  it's a mixture of structrures.
   Is there any solution to this issue？
   thanks！

**Comment by AlexanderSavelyev** [comment]
Hi 
One of possible solutions would be to find the "." symbol in the input string, since "." means a fragment in the format. This solution is slightly dirty though, but it should work
In general, if any input molecular format can be as an input (not only SMILES), I would use the "iterateComponents()" method

https://lifescience.opensource.epam.com/indigo/api/index.html#working-with-connected-components

Thanks
Alexander
