### ISSUE TITLE
Fix max number for elements for Atom List in Ket format

### ISSUE THREAD

**Issue by AlexanderSavelyev** [epam/Indigo#304]
**Acceptance criteria:**
Fix max number for elements for Atom List in Ket format. The max number of elements in list should be infinity

**Comment by SunFellow** [comment]
@AlexanderSavelyev ,
Could you be more specific with Acceptance criteria as we deal with a real programming systems? Otherwise, we are never able to validate the acceptance criteria. 
Staying on 64-bit platform, the maximum number of elements can be limited by one of the following:
- 32-bit index (4,294,967,295)  / 32-bit compatible, theoretical
- Total size of an object aggregating the list/array of atoms read to memory< 2GB  /32-bit compatible), anyway theoretical, since there are other objects an program code.
- Total size of the list/array of atoms serialized to KET file < theoretical max file size at the concrete file system.

- 64-bit index (18,446,744,073,709,551,615), just theoretical
- Total size of an object aggregating the list/array of atoms < 16*2^18 bytes, theoretical either, no such memory.
- Total size of an object aggregating the list/array of atoms < available memory allocated for the process.
- Total size of the list/array of atoms serialized to KET file < theoretical max file size at the concrete file system.

In addition, if we want to handle number of elements more than fit to memory, we need to implement own buffering (swapping) from/to files or database.

**Comment by even1024** [comment]
The issue was related only to json-scheme. Implementation itself doesn't have this limitation.
