### ISSUE TITLE
'Calculated values' - Error messages are different in 'Remote' and 'Standalone' modes

### ISSUE THREAD

**Issue by Svetlana-Asinovskaia** [epam/Indigo#384]
Affected versions: Remote, Standalone

Steps to reproduce:
1. Launch Ketcher (Remote)
2. Execute 'v2/indigo/calculate' with the following parameters:
struct
[Rstruct.zip](https://github.com/epam/Indigo/files/6219972/Rstruct.zip)
options: {smart-layout: true, ignore-stereochemistry-errors: true, mass-skip-error-on-pseudoatoms: false,…}
properties: ["molecular-weight", "most-abundant-mass", "monoisotopic-mass", "gross", "mass-composition"]
3. Repeat steps 1-2 in Standalone mode

Expected result: Error messages are the same in Remote and Standalone modes.
Actual result: Remote mode - 'error: Cannot calculate mass for structure with pseudoatoms, template atoms or RSites'.
Standalone mode - 'mass: Cannot calculate mass for structure with pseudoatoms, template atoms or RSites'.

**Comment by SunFellow** [comment]
Since WASM (Standalone) version is completely reworked against server version, don't expect the literal match of error texts!
Errors and checking are redesigned and reworked as well. 
Just check that the errors are (1) justified and proper for corresponding case, (2) enough clear and properly formulated.

**Comment by even1024** [comment]
fixed in 1.8.0
