### ISSUE TITLE
Bingo Elasticsearch Plugin missing

### ISSUE THREAD

**Issue by bobbrady** [epam/Indigo#513]
Hi Team,
The repo link to the Java ES plugin points to missing code:
https://github.com/epam/Indigo/blob/master/api/plugins/bingo-elastic/java/README.md

There doesn't seem to be an Elasticsearch java plugin code tree any more.  All that seems to remain is an Elasticsearch client for Java and Python.

Has Bingo-ES been changed to do all structure search in the client?  Or has the Elasticsearch plug-in been pulled?  That is, have you closed source the native ES plugin code?

I don't see how a user-land Structure search would scale to a large billion structure set.  Am I interpreting your code base wrong?

Thank you in advance.

**Comment by MysterionRise** [comment]
Thanks for bringing this up @bobbrady, I will take a look into it and fix accordingly soon

**Comment by MysterionRise** [comment]
@bobbrady  fixed README to be linked properly.
Answering to your question, actually we never had Elasticsearch plugin for Bingo, it was rather bad naming initially.

Why we did so? There are lot of Elastic installations available on popular clouds as service. In most of the cases, it's impossible to customise it (one of the examples would be exactly installing plugins). That's why our initial implementation was focused on the client side in order to simplify this kind of deployments. 

Regarding your question about ability to scale, here we are using Elastic as initial candidate filtering, this way we would have less candidates to check on substructure search. We would hope to develop actually plugins to Elasticsearch and Solr accordingly, especially if interest will be great on this one

**Comment by bobbrady** [comment]
@MysterionRise Thank you for your rapid response and detailed info.  Your reasoning for not going the ES plugin route initially makes sense.

I was mistaken about the plugin and will review the README for a basic working example using the ES client.
