### ISSUE TITLE
org.postgresql.util.PSQLException: ERROR: operator does not exist: text @ sub

### ISSUE THREAD

**Issue by sitanshubhunia** [epam/Indigo#527]
Hi,
I am working on project that uses PostgreSQL cartridge. I am able to substructure search in query editor, but when try to run same query from java getting the error.

Query:
**select * from bingo.TABLE where molecule_column @ (bingo.FileToText('D:/qrySDF.sdf'), '')::bingo.sub**
 
Error:
![error](https://user-images.githubusercontent.com/840684/141924408-38c7eaf6-1e85-4000-aed4-226943364c28.png)
****
org.postgresql.util.PSQLException: ERROR: operator does not exist: text @ sub
  Hint: No operator matches the given name and argument type(s). You might need to add explicit type casts.

Please suggest me how to solve this problem still not find a way to overcome this problem.

**Comment by AlexanderSavelyev** [comment]
I was not able to reproduce the issue
Have you installed the bingo cartridge correctly? What does the version return? 

`select` bingo.getversion()

Have you created an index on your table?

Could you try to execute your sql from pgAdmin?
bingo.TABLE looks strange. Is it a table inside the bingo schema?

**Comment by sitanshubhunia** [comment]
I have installed bingo cartridge correctly
select bingo.getversion()
1.9.1.r0-g353401f win64

I have created index
create index prd_index on bingo.productstructure using bingo_idx (molecule_struct bingo.molecule)

I have execute the query from pgAdmin and its return result

Table is under bingo schema

![Table](https://user-images.githubusercontent.com/840684/141979432-b475a3f8-c5de-4331-bdab-b195d63b6fe5.png)
![java](https://user-images.githubusercontent.com/840684/141979440-12ec6c2d-4d6e-41b1-8357-bbf27b03e863.png)

**Comment by AlexanderSavelyev** [comment]
1. It is a bad practice to add a table into the "bingo" scheme because it will be removed together with cartridge
Please read a note here

https://lifescience.opensource.epam.com/bingo/installation-manual-postgres.html#installation-procedure

Note: The installation script creates a new schema (usually bingo),with the default tablespace. Please consider, that the specifying schema will be deleted while calling the uninstall script, thus the installer checks for a schema name and will raise an error if a schema already exists.

2. 
Most probably, your java connect settings does not use the public schema (@ operator is installed into the public schema)
Please try to change the jdbc connection schema or use the following notation

`select .... where .... operator(public.@) ('CC(=O)', '')::bingo.sub `
