### ISSUE TITLE
H-contained binary compounds don`t match SMARTS

### ISSUE THREAD

**Issue by AATDev21** [epam/Indigo#557]
Inorganic compounds, consist of any atom except carbon and any number of hydrogen atoms,
didn`t match appropriate SMARTS.

Compounds example: HCl (hydrogen chloride).
SMARTS: [*X1&!#1&!#6]~[*X1&!#6].

Steps to reproduce:
Try to check if any mixture contains hydrogen chloride like this:
`m = self.indigo.loadMolecule('Cl.C')`
`self.assertTrue(m.checkSalt(), '{} contains hydrogen chloride.'.format(m.smiles()))`

Expected result:
True.

Obtained result:
AssertionError: False is not true.

AssertionErrors occurred with similar compounds like H2S, NH3, SiH4.

**Comment by mkviatkovskii** [comment]
Dear @AATDev21,
According to [Daylight SMARTS tutorial](https://www.daylight.com/dayhtml_tutorials/languages/smarts/), `*` is treated as "any atom except hydrogen", that's the reason the query is not matched in your case. Some other implementations can operate in other way, because [another Daylight SMARTS description page](https://www.daylight.com/dayhtml/doc/theory/theory.smarts.html) says just "any atom". 

So in this case, please just modify SMARTS to
```
[X1&!#1&!#6]~[X1&!#6]
```
And it will work correctly.
