### ISSUE TITLE
Please add the command that installs the whole system

### ISSUE THREAD

**Issue by yurivict** [epam/Indigo#95]
There are directories with cmake projects which build, but they don't have 'install' targets. It isn't clear how to install the whole system. There are two commands in README that build installation archives, but it isn't clear how to actually install them.

Please create or document the command that installs the whole system into the directory provided by the user. I would like to install it into /usr/local.

**Comment by mkviatkovskii** [comment]
Hello @yurivict,
Could you please clarify what do you mean by "the whole system". Indigo consists of very different tools:

* Native command-line utils (indigo-depict, indigo-cano, indigo-deco)
* Java-based GUI utils (chemdiff, legio)
* Shared libraries (libindigo.so, libindigo-renderer.so, libindigo-inchi.so, libbingo-nosql.so)
* Java, Python and C# wrappers to the libraries (indigo-java, indigo-python, indigo-dotnet)
* Bingo chemical cartridges to Oracle, PostgreSQL and Microsoft SQL Server.

Some of them are tricky to install because of external dependencies. So I guess you may mean native command-line utils and native libraries, could you please confirm or correct it?

**Comment by MysterionRise** [comment]
@mkviatkovskii @AlexanderSavelyev  is it still relevant?
