### ISSUE TITLE
Unexpected behavior during SMILES canonicalization

### ISSUE THREAD

**Issue by jstaker7** [epam/Indigo#96]
I have two SMILES that are virtually equivalent, and result in identical structures:

CC1C=C(N=C(C)C=1C)C1(N=C(N)C2=C(F)C=CC=C12)C1C=C(N=CC=1)C1C=NC=C(F)C=1
CC1N=C(C=C(C)C=1C)C1(N=C(N)C2=C(F)C=CC=C12)C1C=C(N=CC=1)C1C=NC=C(F)C=1

But when canonicalizing these using Indigo, they result in different SMILES strings. Is this expected behavior or indicative of a bug?

**Comment by IuriiPuzanov** [comment]
Hello Josh,

   Thank you very much for your interest to Indigo!
As about you question the answer is yes, this is expected behavior.
In classic form these structures are different and corresponding canonical SMILES are different also. But if you aromatize these structures and then generate canonical SMILES the results will be identical.

Best Regards!
Yuriy.
